repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: js-check
        name: JS style and lint
        description: Run semistandard on files included in the commit.
        entry: ./scripts/js-check.sh
        pass_filenames: true
        types: [file, javascript]
        language: system
    -   id: commit-lint
        name: Commit Lint
        description: Runs commitlint against the commit message.
        language: system
        entry: bash -c "npm install --no-save @commitlint/config-conventional @commitlint/cli; cat $1 | npx commitlint"
        args: [$1]
        stages: [commit-msg]
